Update JAMIL_DNS

diff --git a/JAMIL_DNS b/JAMIL_DNS
--- a/JAMIL_DNS
+++ b/JAMIL_DNS
@@ -1,79 +1,65 @@
-#!/bin/bash
+NS='protw2.xd.parokya.online'
+NS1='br1.tunnel.cx'
+NS2='ns-ph2.vpnjz.com'
+NS3='ns-my4.vpnjantit.com'
+NS4='ns-sg3.slowdns.me'
 
-# Improved DNSTT Keep-Alive Script
-# Copyright ©UDPTeam
-# Recoded by: Jamil Aliso
-
-# Your DNSTT Nameservers
-declare -a NAMESERVERS=('ns.phvxsqmbql.ssh-websurf.cloud' 'sg1-dns.microsshsvr.host' 'sg1-ns.jkimdns.com' 'sg2-ns.jkimdns.com' 'priv-sg.ns.jkimdns.com')
-# Your Domain `A` Record
-A_RECORD='jkimdns.com'
-
-# Add your DNS here
-declare -a HOSTS=('124.6.181.12' '124.6.181.20' '124.6.181.4' '124.6.181.36')
-
-# Loop delay in seconds (positive integer only)
 LOOP_DELAY=5
-if ! [[ "$LOOP_DELAY" =~ ^[1-9][0-9]*$ ]]; then
-    echo "Invalid LOOP_DELAY. Must be a positive integer."
-    exit 1
-fi
 
-# Check and set the dig command
-DIG_EXEC=${DIG_EXEC:-"DEFAULT"} # Use DEFAULT if not set
-CUSTOM_DIG='/data/data/com.termux/files/home/go/bin/fastdig'
+declare -a HOSTS=('124.6.181.12'124.6.181.20')
+DIG_EXEC="DEFAULT"
 
-# Determine the dig command based on user choice
-DIG_CMD=""
+CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig
+
+######################################
+######################################
+######################################
+######################################
+######################################
+VER=0.1
 case "${DIG_EXEC}" in
-    DEFAULT|D) DIG_CMD="$(command -v dig)" ;;
-    CUSTOM|C) DIG_CMD="${CUSTOM_DIG}" ;;
-    *) echo "Invalid DIG_EXEC value. Please choose DEFAULT or CUSTOM."; exit 1 ;;
+ DEFAULT|D)
+ _DIG="$(command -v dig)"
+ ;;
+ CUSTOM|C)
+ _DIG="${CUSTOM_DIG}"
+ ;;
 esac
-
-# Verify that dig command is available
-if [ -z "${DIG_CMD}" ]; then
-    echo "Dig command not found. Please install dnsutils or set the correct path in CUSTOM_DIG."
-    exit 1
+if [ ! $(command -v ${_DIG}) ]; then
+ printf "%b" "Dig command failed to run, " \
+ "please install dig(dnsutils) or check " \
+ "\$DIG_EXEC & \$CUSTOM_DIG variable inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n" && exit 1
 fi
-
-# Function to end the script
-function end_script() {
-    echo "Exiting script."
-    exit 0
+endscript() {
+ unset NS A LOOP_DELAY HOSTS _DIG DIG_EXEC CUSTOM_DIG T R M
+ exit 1
 }
-
-# Trap SIGINT and SIGTERM
-trap end_script SIGINT SIGTERM
-
-# Function to check the DNS
-function check_dns() {
-    for host in "${HOSTS[@]}"; do
-        for ns in "${NAMESERVERS[@]}" "${A_RECORD}"; do
-            if [ -z "$(timeout -k 3 3 ${DIG_CMD} @${host} ${ns} 2> /dev/null)" ]; then
-                echo "R:${ns} D:${host} - Success"
-            else
-                echo "R:${ns} D:${host} - Success"
-            fi
-        done
-    done
+trap endscript 2 15
+check(){
+ for ((i=0; i<"${#HOSTS[*]}"; i++)); do
+  for R in "${NS}" "${A}" "${NS1}" "${A1}" "${NS2}" "${A2}" "${NS3}" "${A3}" "${NS4}" "${A4}"; do
+   T="${HOSTS[$i]}"
+     $(timeout -k .3 .3 ${_DIG} @${T} ${R})  && M=31 || M=32;
+   echo -e "\e[1;${M}m\$ R:${R} D:${T}\e[0m"
+   unset T R M
+  done
+ done
 }
-
-# Main execution
-echo "DNSTT Keep-Alive script Modified by: Jamil Aliso"
-echo "DNS List: ${HOSTS[*]}"
+echo "DNSTT Keep-Alive script <Discord @civ3>"
+echo -e "DNS List: [\e[1;34m${HOSTS[*]}\e[0m]"
 echo "CTRL + C to close script"
-
-# Loop or single check based on argument
-if [ "$1" == "loop" ] || [ "$1" == "l" ]; then
-    echo "Script loop: ${LOOP_DELAY} seconds"
-    while true; do
-        check_dns
-        echo '---------------------------------'
-        sleep ${LOOP_DELAY}
-    done
-else
-    check_dns
-fi
-
+ "${LOOP_DELAY}" -eq 1  && let "LOOP_DELAY++";
+case "${@}" in
+ loop|l)
+ echo "Script loop: ${LOOP_DELAY} seconds"
+ while true; do
+  check
+  echo '.--. .-.. . .- ... .     .-- .- .. -'
+  sleep ${LOOP_DELAY}
+ done
+ ;;
+ *)
+ check
+ ;;
+esac
 exit 0
